name: example-environment
channels:
  - conda-forge
dependencies:
  - ipympl
  - nodejs
  - ffmpeg
  - python=3.10.4
  - matplotlib=3.5.2
  - numpy=1.22.3
  - scipy=1.8.0
  - jupyter_contrib_nbextensions=0.5.1
  - ipywidgets=7.7.0
